### ISSUE TITLE
ccsh-shell shitted the bed

### ISSUE THREAD

**Issue by SolarAquarion** [cpp-ftw/ccsh#9]
Scanning dependencies of target ccsh
[ 86%] Building CXX object ui/CMakeFiles/ccsh.dir/ccsh_ui.cpp.o
In file included from /opt/cling/include/clang/Basic/FileManager.h:20:0,
                 from /opt/cling/include/clang/Basic/SourceManager.h:38,
                 from /opt/cling/include/clang/Frontend/CompilerInstance.h:16,
                 from /home/solaraquarion/build/ccsh-shell-git/src/ccsh/ui/ccsh_ui.cpp:16:
/opt/cling/include/clang/Basic/VirtualFileSystem.h:36:14: error: ‘TimeValue’ in namespace ‘llvm::sys’ does not name a type
   llvm::sys::TimeValue MTime;
              ^~~~~~~~~
/opt/cling/include/clang/Basic/VirtualFileSystem.h:50:21: error: ‘llvm::sys::TimeValue’ has not been declared
          llvm::sys::TimeValue MTime, uint32_t User, uint32_t Group,
                     ^~~~~~~~~
/opt/cling/include/clang/Basic/VirtualFileSystem.h:66:14: error: ‘TimeValue’ in namespace ‘llvm::sys’ does not name a type
   llvm::sys::TimeValue getLastModificationTime() const { return MTime; }
              ^~~~~~~~~
In file included from /opt/cling/include/clang/Frontend/CompilerInstance.h:16:0,
                 from /home/solaraquarion/build/ccsh-shell-git/src/ccsh/ui/ccsh_ui.cpp:16:
/opt/cling/include/clang/Basic/SourceManager.h:230:17: error: ‘AlignOf’ is not a member of ‘llvm’
   static_assert(llvm::AlignOf<ContentCache>::Alignment >= 8,
                 ^~~~
/opt/cling/include/clang/Basic/SourceManager.h:230:43: error: expected primary-expression before ‘>’ token
   static_assert(llvm::AlignOf<ContentCache>::Alignment >= 8,
                                           ^
/opt/cling/include/clang/Basic/SourceManager.h:230:44: error: ‘::Alignment’ has not been declared
   static_assert(llvm::AlignOf<ContentCache>::Alignment >= 8,
                                            ^~
/opt/cling/include/clang/Basic/SourceManager.h:230:44: note: suggested alternative:
In file included from /opt/cling/include/clang/Basic/LangOptions.h:21:0,
                 from /home/solaraquarion/build/ccsh-shell-git/src/ccsh/ui/ccsh_ui.cpp:15:
/opt/cling/include/clang/Basic/Sanitizers.def:57:24: note:   ‘clang::SanitizerKind::Alignment’
 SANITIZER("alignment", Alignment)
                        ^
/opt/cling/include/clang/Basic/Sanitizers.h:40:23: note: in definition of macro ‘SANITIZER’
   const SanitizerMask ID = 1ULL << SO_##ID;
                       ^~
In file included from /opt/cling/include/clang/Basic/Diagnostic.h:23:0,
                 from /opt/cling/include/clang/Frontend/CompilerInstance.h:15,
                 from /home/solaraquarion/build/ccsh-shell-git/src/ccsh/ui/ccsh_ui.cpp:16:
/usr/include/llvm/ADT/DenseMap.h: In instantiation of ‘void llvm::DenseMapBase<DerivedT, KeyT, ValueT, KeyInfoT, BucketT>::destroyAll() [with DerivedT = llvm::SmallDenseMap<std::__cxx11::basic_string<char>, llvm::detail::DenseSetEmpty, 16u, llvm::DenseMapInfo<std::__cxx11::basic_string<char> >, llvm::detail::DenseSetPair<std::__cxx11::basic_string<char> > >; KeyT = std::__cxx11::basic_string<char>; ValueT = llvm::detail::DenseSetEmpty; KeyInfoT = llvm::DenseMapInfo<std::__cxx11::basic_string<char> >; BucketT = llvm::detail::DenseSetPair<std::__cxx11::basic_string<char> >]’:
/usr/include/llvm/ADT/DenseMap.h:783:5:   required from ‘llvm::SmallDenseMap<KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT>::~SmallDenseMap() [with KeyT = std::__cxx11::basic_string<char>; ValueT = llvm::detail::DenseSetEmpty; unsigned int InlineBuckets = 16u; KeyInfoT = llvm::DenseMapInfo<std::__cxx11::basic_string<char> >; BucketT = llvm::detail::DenseSetPair<std::__cxx11::basic_string<char> >]’
/usr/include/llvm/ADT/DenseSet.h:47:7:   required from here
/usr/include/llvm/ADT/DenseMap.h:307:29: error: ‘isEqual’ is not a member of ‘llvm::DenseMapInfo<std::__cxx11::basic_string<char> >’
       if (!KeyInfoT::isEqual(P->getFirst(), EmptyKey) &&
            ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/llvm/ADT/DenseMap.h:308:29: error: ‘isEqual’ is not a member of ‘llvm::DenseMapInfo<std::__cxx11::basic_string<char> >’
           !KeyInfoT::isEqual(P->getFirst(), TombstoneKey))
            ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/llvm/ADT/DenseMap.h: In instantiation of ‘static const KeyT llvm::DenseMapBase<DerivedT, KeyT, ValueT, KeyInfoT, BucketT>::getEmptyKey() [with DerivedT = llvm::SmallDenseMap<std::__cxx11::basic_string<char>, llvm::detail::DenseSetEmpty, 16u, llvm::DenseMapInfo<std::__cxx11::basic_string<char> >, llvm::detail::DenseSetPair<std::__cxx11::basic_string<char> > >; KeyT = std::__cxx11::basic_string<char>; ValueT = llvm::detail::DenseSetEmpty; KeyInfoT = llvm::DenseMapInfo<std::__cxx11::basic_string<char> >; BucketT = llvm::detail::DenseSetPair<std::__cxx11::basic_string<char> >]’:
/usr/include/llvm/ADT/DenseMap.h:305:38:   required from ‘void llvm::DenseMapBase<DerivedT, KeyT, ValueT, KeyInfoT, BucketT>::destroyAll() [with DerivedT = llvm::SmallDenseMap<std::__cxx11::basic_string<char>, llvm::detail::DenseSetEmpty, 16u, llvm::DenseMapInfo<std::__cxx11::basic_string<char> >, llvm::detail::DenseSetPair<std::__cxx11::basic_string<char> > >; KeyT = std::__cxx11::basic_string<char>; ValueT = llvm::detail::DenseSetEmpty; KeyInfoT = llvm::DenseMapInfo<std::__cxx11::basic_string<char> >; BucketT = llvm::detail::DenseSetPair<std::__cxx11::basic_string<char> >]’
/usr/include/llvm/ADT/DenseMap.h:783:5:   required from ‘llvm::SmallDenseMap<KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT>::~SmallDenseMap() [with KeyT = std::__cxx11::basic_string<char>; ValueT = llvm::detail::DenseSetEmpty; unsigned int InlineBuckets = 16u; KeyInfoT = llvm::DenseMapInfo<std::__cxx11::basic_string<char> >; BucketT = llvm::detail::DenseSetPair<std::__cxx11::basic_string<char> >]’
/usr/include/llvm/ADT/DenseSet.h:47:7:   required from here
/usr/include/llvm/ADT/DenseMap.h:392:33: error: ‘getEmptyKey’ is not a member of ‘llvm::DenseMapInfo<std::__cxx11::basic_string<char> >’
     return KeyInfoT::getEmptyKey();
            ~~~~~~~~~~~~~~~~~~~~~^~
/usr/include/llvm/ADT/DenseMap.h: In instantiation of ‘static const KeyT llvm::DenseMapBase<DerivedT, KeyT, ValueT, KeyInfoT, BucketT>::getTombstoneKey() [with DerivedT = llvm::SmallDenseMap<std::__cxx11::basic_string<char>, llvm::detail::DenseSetEmpty, 16u, llvm::DenseMapInfo<std::__cxx11::basic_string<char> >, llvm::detail::DenseSetPair<std::__cxx11::basic_string<char> > >; KeyT = std::__cxx11::basic_string<char>; ValueT = llvm::detail::DenseSetEmpty; KeyInfoT = llvm::DenseMapInfo<std::__cxx11::basic_string<char> >; BucketT = llvm::detail::DenseSetPair<std::__cxx11::basic_string<char> >]’:
/usr/include/llvm/ADT/DenseMap.h:305:72:   required from ‘void llvm::DenseMapBase<DerivedT, KeyT, ValueT, KeyInfoT, BucketT>::destroyAll() [with DerivedT = llvm::SmallDenseMap<std::__cxx11::basic_string<char>, llvm::detail::DenseSetEmpty, 16u, llvm::DenseMapInfo<std::__cxx11::basic_string<char> >, llvm::detail::DenseSetPair<std::__cxx11::basic_string<char> > >; KeyT = std::__cxx11::basic_string<char>; ValueT = llvm::detail::DenseSetEmpty; KeyInfoT = llvm::DenseMapInfo<std::__cxx11::basic_string<char> >; BucketT = llvm::detail::DenseSetPair<std::__cxx11::basic_string<char> >]’
/usr/include/llvm/ADT/DenseMap.h:783:5:   required from ‘llvm::SmallDenseMap<KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT>::~SmallDenseMap() [with KeyT = std::__cxx11::basic_string<char>; ValueT = llvm::detail::DenseSetEmpty; unsigned int InlineBuckets = 16u; KeyInfoT = llvm::DenseMapInfo<std::__cxx11::basic_string<char> >; BucketT = llvm::detail::DenseSetPair<std::__cxx11::basic_string<char> >]’
/usr/include/llvm/ADT/DenseSet.h:47:7:   required from here
/usr/include/llvm/ADT/DenseMap.h:395:37: error: ‘getTombstoneKey’ is not a member of ‘llvm::DenseMapInfo<std::__cxx11::basic_string<char> >’
     return KeyInfoT::getTombstoneKey();
            ~~~~~~~~~~~~~~~~~~~~~~~~~^~
make[2]: *** [ui/CMakeFiles/ccsh.dir/build.make:63: ui/CMakeFiles/ccsh.dir/ccsh_ui.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:275: ui/CMakeFiles/ccsh.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by dobragab** [comment]
Confirmed.

On Arch LLVM 4.0 is already released, and cling-git picks global llvm headers. But cling headers are still based on LLVM 3.9. So this is an issue caused by cling-git, and not by ccsh-shell-git.

I'll report this once I have time.

**Comment by dobragab** [comment]
Does the problem still exist?

**Comment by SolarAquarion** [comment]
no
